---
title: "Graphics for oligo"
author: "tanunia"
date: "12/09/2014"
output: html_document
---


Load prepared data
```{r}
prepared_data <- read.table("../data/features_oligo.tsv", sep = "\t", header=TRUE)
totalTable <- NULL
totalTable$sd <- prepared_data$sd
totalTable$mean <- prepared_data$mean
```

(3) Graphics for foward primer features
```{r}
library(lattice)
xyplot(totalTable$mean ~ prepared_data$Tm_fwd,  xlab="Tm", ylab="mean of amplicon percental amount", main="Forward Primer")
xyplot(totalTable$mean ~ prepared_data$dG_fwd,  xlab="dG", ylab="mean of amplicon percental amount", main="Forward Primer ")
xyplot(log(totalTable$mean) ~ prepared_data$dH_fwd,  xlab="dH", ylab="mean of amplicon percental amount", main="Forward Primer")
xyplot(log(totalTable$mean) ~ prepared_data$dS_fwd,  xlab="dS", ylab="mean of amplicon percental amount", main="Forward Primer")

```

(3) Graphics for foward primer features
```{r}
xyplot(totalTable$mean ~ prepared_data$Tm_fwd,  xlab="Tm", ylab="mean of amplicon percental amount", main="Forward Primer")
xyplot(totalTable$mean ~ prepared_data$dG_fwd,  xlab="dG", ylab="mean of amplicon percental amount", main="Forward Primer ")
xyplot(log(totalTable$mean) ~ prepared_data$dH_fwd,  xlab="dH", ylab="mean of amplicon percental amount", main="Forward Primer")
xyplot(log(totalTable$mean) ~ prepared_data$dS_fwd,  xlab="dS", ylab="mean of amplicon percental amount", main="Forward Primer")

```

(3) Graphics for reverse primer features
```{r}
xyplot(totalTable$sd ~ prepared_data$Tm_rev,  xlab="Tm", ylab="sd of amplicon percental amount", main="Reverse Primer")
xyplot(totalTable$sd ~ prepared_data$dG_rev,  xlab="dG", ylab="sd of amplicon percental amount", main="Reverse Primer ")
xyplot(log(totalTable$sd) ~ prepared_data$dH_rev,  xlab="dH", ylab="sd of amplicon percental amount", main="Reverse Primer")
xyplot(log(totalTable$sd) ~ prepared_data$dS_rev,  xlab="dS", ylab="sd of amplicon percental amount", main="Reverse Primer")
```

(3) Graphics for reverse primer features
```{r}
xyplot(totalTable$sd ~ prepared_data$Tm_rev,  xlab="Tm", ylab="sd of amplicon percental amount", main="Reverse Primer")
xyplot(totalTable$sd ~ prepared_data$dG_rev,  xlab="dG", ylab="sd of amplicon percental amount", main="Reverse Primer ")
xyplot(log(totalTable$sd) ~ prepared_data$dH_rev,  xlab="dH", ylab="sd of amplicon percental amount", main="Reverse Primer")
xyplot(log(totalTable$sd) ~ prepared_data$dS_rev,  xlab="dS", ylab="sd of amplicon percental amount", main="Reverse Primer")
```

Different feature selection tests
```{r}
library(lattice)
library(FSelector)
histogram(prepared_data$sd)
sd(prepared_data$sd)
formula <- sd ~ Amplicon_Len + Amplicon_GC_content + Fwd_END_3 + Rev_END_3+Start_Dangling_End+Stop_Dangling_End + Fwd_Primer_Len +Fwd_Primer_GC_content+ Rev_Primer_Len +Rev_Primer_GC_content + Fwd_Primer_MaxPolyX + Rev_Primer_MaxPolyX + Amplicon_MaxPolyX + Fwd_Primer_Entropy + Rev_Primer_Entropy + Amplicon_Entropy + Fwd_Primer_Hash + Rev_Primer_Hash + Amplicon_Hash + Tm_fwd +dG_fwd +dH_fwd +dS_fwd + Tm_rev +dG_rev +dH_rev +dS_rev
chi.squared(formula, data = prepared_data)
chi <- chi.squared(formula, data = prepared_data)
chi$names <- rownames(chi)
chi <- chi[order(-chi$attr_importance), ]
barchart( chi$names ~ chi$attr_importance, main = "Chi-squared test", xlab = "Feature improtance")
information.gain(formula, data = prepared_data)
gain.ratio(formula, data = prepared_data)
symmetrical.uncertainty(formula, data = prepared_data)
oneR(formula, data = prepared_data)
random.forest.importance(formula, data = prepared_data, importance.type = 1)
```


```{r}
library(FSelector)
histogram(prepared_data$mean)
sd(prepared_data$mean)
formula <- mean ~ Amplicon_Len + Amplicon_GC_content + Fwd_END_3 + Rev_END_3+Start_Dangling_End+Stop_Dangling_End + Fwd_Primer_Len +Fwd_Primer_GC_content+ Rev_Primer_Len +Rev_Primer_GC_content + Fwd_Primer_MaxPolyX + Rev_Primer_MaxPolyX + Amplicon_MaxPolyX + Fwd_Primer_Entropy + Rev_Primer_Entropy + Amplicon_Entropy + Fwd_Primer_Hash + Rev_Primer_Hash + Amplicon_Hash + Tm_fwd +dG_fwd +dH_fwd +dS_fwd + Tm_rev +dG_rev +dH_rev +dS_rev
chi.squared(formula, data = prepared_data)
chi <- chi.squared(formula, data = prepared_data)
chi$names <- rownames(chi)
chi <- chi[order(-chi$attr_importance), ]
barchart( chi$names ~ chi$attr_importance, main = "Chi-squared test", xlab = "Feature improtance")
information.gain(formula, data = prepared_data)
gain.ratio(formula, data = prepared_data)
symmetrical.uncertainty(formula, data = prepared_data)
oneR(formula, data = prepared_data)
random.forest.importance(formula, data = prepared_data, importance.type = 1)
```

Feature subset selection tests
```{r}
library(corrplot)
prepared_data_num <- prepared_data
prepared_data_num$Start_Dangling_End <- as.numeric(prepared_data_num$Start_Dangling_End)
prepared_data_num$Stop_Dangling_End <- as.numeric(prepared_data_num$Stop_Dangling_End)
prepared_data_num$Fwd_END_3 <- as.numeric(prepared_data_num$Fwd_END_3)
prepared_data_num$Rev_END_3 <- as.numeric(prepared_data_num$Rev_END_3)
prepared_data_num$res <- NULL
prepared_data_num$logres <- NULL
prepared_data_num$MeansSD <- NULL
print(ncol(prepared_data_num))
prepared_data.scale<- scale(prepared_data_num[2:ncol(prepared_data_num)], center=TRUE, scale=TRUE)
cor_prepared_data <- cor(prepared_data.scale)
corrplot(cor_prepared_data, order = "original")
library(cvTools)
library(caret)
# control <- trainControl(method="repeatedcv", number=10, repeats=3)
# model <- train(res~., data=prepared_data, method="lvq", preProcess="scale", trControl=control)
# # estimate variable importance
# importance <- varImp(model, scale=FALSE)
# # summarize importance
# print(importance)
# # plot importance
# plot(importance)
evaluator <- function(subset) {
    formula <- mean ~ . 
    valid_names <- c(subset,"res")
    rf <- randomForest(formula, prepared_data[,valid_names])
    result <- cvFit(rf, data =  prepared_data[,valid_names], y =  prepared_data[,valid_names]$res, cost = rtmspe,
        K = 5, R = 10, costArgs = list(trim = 0.1), seed = 1234)
    return(1-result$cv)
}

#perform the best subset search
#subset <- exhaustive.search(names(prepared_data[-c(1, 11)]), evaluator)
#subset <- best.first.search(names(prepared_data[-c(1, 11)]), evaluator)
```
